#### Obtener todos los productos

GET http://localhost:8080/api/productos
Accept: application/json


### Crear un nuevo producto

POST http://localhost:8080/api/productos
Content-Type: application/json

{
    "nombre": "Laptop Tuf Gaming",
    "precio": 4300000.3,
    "stock": 15,
    "descripcion": "Es una laptop marca lenovo"
}

